-- 0005_invitations.sql
--
-- Phase 2: coach → client invitations. A coach creates a pending, single-use,
-- time-boxed invitation. The invitee never reads invitations directly — an Edge
-- Function (service role) resolves the token and performs the assignment. Status
-- transitions (accept/revoke/expire) and the coach_id write are server-side only
-- (CLAUDE.md §2). Idempotent so it can be safely re-applied in the SQL editor.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'invitation_status') then
    create type public.invitation_status as enum ('pending', 'accepted', 'revoked', 'expired');
  end if;
end
$$;

create table if not exists public.invitations (
  id          uuid primary key default gen_random_uuid(),
  coach_id    uuid not null references public.profiles (id) on delete cascade,
  email       text not null,
  -- Opaque, unguessable, single-use token (server-generated by default).
  token       uuid not null default gen_random_uuid(),
  status      public.invitation_status not null default 'pending',
  expires_at  timestamptz not null default (now() + interval '7 days'),  -- UTC (§11)
  created_at  timestamptz not null default now(),
  accepted_at timestamptz,
  accepted_by uuid references public.profiles (id) on delete set null,
  constraint invitations_token_unique unique (token)
);

create index if not exists invitations_coach_id_idx on public.invitations (coach_id);

alter table public.invitations enable row level security;

-- Read: a coach sees only their own invitations; admins see all. The invitee does
-- NOT read here — token resolution happens server-side via the service role.
drop policy if exists invitations_select on public.invitations;
create policy invitations_select on public.invitations
  for select to authenticated
  using (
    coach_id = auth.uid()
    or public.current_app_role() = 'admin'
  );

-- Create: a coach creates only their OWN invitation, only as 'pending', and may
-- not pre-set acceptance fields. Token/status/expiry/timestamps come from defaults.
drop policy if exists invitations_insert on public.invitations;
create policy invitations_insert on public.invitations
  for insert to authenticated
  with check (
    coach_id = auth.uid()
    and public.current_app_role() = 'coach'
    and status = 'pending'
    and accepted_at is null
    and accepted_by is null
  );

-- No UPDATE / DELETE policy on purpose: status transitions and the resulting
-- coach_id assignment are written ONLY by the service role inside Edge Functions
-- (§2). deny-by-default blocks every client/coach write here.

grant select, insert on public.invitations to authenticated;
grant select on public.invitations to anon;  -- RLS -> 0 rows for anon
